### ISSUE TITLE
your class names need to be Camelized

### ISSUE THREAD

**Issue by thecodechef** [jakejarrett/albert-themes#1]
bottomframe => bottomFrame
topframe => topFrame
inputline => inputLine
settingsbutton => settingsButton
proposallist => proposalList

**Comment by jakejarrett** [comment]
Thanks @thecodechef I'll update them tonight :smile_cat:

**Comment by jakejarrett** [comment]
Pushed camel case versions of the qss files @thecodechef 

e4302b8
